# 00. TensorFlow Fundamentals Exercises

In [1]:
import tensorflow as tf

### 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().

In [4]:
vector = tf.constant([1, 2, 3, 4, 5])
vector

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5])>

In [5]:
vector.ndim

1

In [8]:
scalar = tf.constant(1)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [9]:
scalar.ndim

0

In [10]:
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]])>

In [11]:
matrix.ndim

2

In [12]:
tensor = tf.constant([[[1,2],
                       [3,4]],
                      
                      [[11,12],
                       [13,14]]
                     ])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 1,  2],
        [ 3,  4]],

       [[11, 12],
        [13, 14]]])>

In [13]:
tensor.ndim

3

### 2. Find the shape, rank and size of the tensors you created in 1

In [16]:
tensor.shape, tf.rank(tensor), tf.size(tensor)

(TensorShape([2, 2, 2]),
 <tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(), dtype=int32, numpy=8>)

### 3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.

In [18]:
tf.random.set_seed(42)

random_1 = tf.random.uniform(shape=(5,300))
random_2 = tf.random.uniform(shape=(5,300))

In [19]:
random_1, random_2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.6645621 , 0.44100678, 0.3528825 , ..., 0.31410468, 0.7593535 ,
         0.03699052],
        [0.532024  , 0.29129946, 0.10571766, ..., 0.54052293, 0.31425726,
         0.2200619 ],
        [0.08404207, 0.03614604, 0.97732127, ..., 0.21516645, 0.9786098 ,
         0.00726748],
        [0.7396945 , 0.6653172 , 0.0787828 , ..., 0.7117733 , 0.07013571,
         0.9409125 ],
        [0.15861344, 0.12024033, 0.27218235, ..., 0.8824879 , 0.1432488 ,
         0.44135118]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.68789124, 0.48447883, 0.9309944 , ..., 0.6920762 , 0.33180213,
         0.9212563 ],
        [0.27369928, 0.10631859, 0.6218617 , ..., 0.4382149 , 0.30427706,
         0.51477313],
        [0.00920248, 0.37280262, 0.8177401 , ..., 0.56786287, 0.49201214,
         0.9892651 ],
        [0.88608265, 0.08672249, 0.12160683, ..., 0.91770685, 0.72545695,
         0.8280058 ],
        [0.36690

In [20]:
random_1.shape, random_2.shape

(TensorShape([5, 300]), TensorShape([5, 300]))

### 4. Multiply the two tensors you created in 3 using matrix multiplication.

In [22]:
tf.matmul(random_1, tf.transpose(random_2) )

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40499 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.602066],
       [79.7594  , 75.644554, 77.79758 , 74.74873 , 80.55984 ],
       [75.08526 , 69.064064, 74.30776 , 72.27615 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00686 , 74.88679 , 83.13417 ]],
      dtype=float32)>

### 5. Multiply the two tensors you created in 3 using dot product.

In [26]:
tf.tensordot(random_1, tf.transpose(random_2), axes = 1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[80.33345 , 73.40499 , 77.159615, 73.98369 , 80.90053 ],
       [75.146355, 68.80437 , 74.24302 , 71.841835, 75.602066],
       [79.7594  , 75.644554, 77.79758 , 74.74873 , 80.55984 ],
       [75.08526 , 69.064064, 74.30776 , 72.27615 , 76.05669 ],
       [85.05688 , 74.26627 , 78.00686 , 74.88679 , 83.13417 ]],
      dtype=float32)>

### 6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.

In [27]:
random_3 = tf.random.uniform(shape=(224,224,3))
random_3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.7413678 , 0.62854624, 0.01738465],
        [0.3431449 , 0.51063764, 0.3777541 ],
        [0.07321596, 0.02137029, 0.2871771 ],
        ...,
        [0.98953485, 0.45382905, 0.2006687 ],
        [0.6295223 , 0.4937899 , 0.01816809],
        [0.95386636, 0.11542463, 0.85691285]],

       [[0.78435016, 0.7826872 , 0.87936425],
        [0.24906898, 0.3207239 , 0.10955775],
        [0.543224  , 0.7151396 , 0.40334642],
        ...,
        [0.2445668 , 0.01746976, 0.9036933 ],
        [0.02975535, 0.592268  , 0.9877522 ],
        [0.36701274, 0.33112562, 0.5638567 ]],

       [[0.15829337, 0.7288823 , 0.3366307 ],
        [0.70792687, 0.16910625, 0.9429966 ],
        [0.10120225, 0.5919596 , 0.8687303 ],
        ...,
        [0.28134012, 0.10011208, 0.37038183],
        [0.77874243, 0.05421627, 0.4664607 ],
        [0.2549187 , 0.7968637 , 0.83405185]],

       ...,

       [[0.32922816, 0.06343532, 0.23936498],
        [0.42

### 7. Find the min and max values of the tensor you created in 6 along the first axis.

In [30]:
tf.reduce_min(random_3)

<tf.Tensor: shape=(), dtype=float32, numpy=2.3841858e-07>

In [31]:
tf.reduce_max(random_3)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9999918>

### 8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.

In [32]:
ten = tf.random.uniform(shape=(1,224,224,3))
ten.shape

TensorShape([1, 224, 224, 3])

In [33]:
ten_squeezed = tf.squeeze(ten)
ten_squeezed.shape

TensorShape([224, 224, 3])

### 9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.

In [34]:
import numpy as np

In [35]:
my_ten = tf.constant(np.random.random(10))
my_ten

<tf.Tensor: shape=(10,), dtype=float64, numpy=
array([0.56389655, 0.16388109, 0.9065678 , 0.91986917, 0.10156039,
       0.35448341, 0.03437443, 0.85241231, 0.91554875, 0.67414422])>

In [36]:
tf.argmax(my_ten)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [37]:
tf.reduce_max(my_ten)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9198691733811569>

In [38]:
my_ten[tf.argmax(my_ten)]

<tf.Tensor: shape=(), dtype=float64, numpy=0.9198691733811569>

### 10. One-hot encode the tensor you created in 9.

In [45]:
tf.one_hot(np.arange(1,10,2), depth=5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [48]:
t1 = tf.constant([[10,7],
                  [7,10]])

t2 = tf.constant([[10, 20],
                 [30, 10]])

# Elementwise computes the bitwise AND of x and y.
tf.bitwise.bitwise_and(t1, t2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  4],
       [ 6, 10]])>

In [49]:
month_purches = tf.constant([[2, 3, 5],
                             [5, 1, 2],
                             [14, 3, 9]])

price = tf.constant([10,6,8])

In [53]:
# bill per month
month_bill = tf.tensordot(price, month_purches, axes=1)
month_bill

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([162,  60, 134])>

In [54]:
# total bill of 3 month
total_3 = tf.reduce_sum(month_bill)

In [55]:
total_3

<tf.Tensor: shape=(), dtype=int32, numpy=356>